// All the components to be exported individually
module.exports = [
  'classes',
  'If',
  'Button/Button',
  'Card/Card',
  'CardsList/CardsList',
  'ContentWrapper/ContentWrapper',
  'Footer/Footer',
  'Header/Header',
  'Icon/Icon',
  'Link/Link',
  'ProgressBar/ProgressBar',
  'RatingStars/RatingStars',
  'Review/Review',
  'ReviewList/ReviewList',
  'SnapPage/SnapPageAbout',
  'SnapPage/SnapPageConfirm',
  'SnapPage/SnapPageDetails',
  'SnapPage/SnapPageInstallButton',
  'SnapPage/SnapPageInterfaces',
  'SnapPage/SnapPageLogin',
  'SnapPage/SnapPagePurchase',
  'SnapPage/SnapPageSummary',
  'SnapPage/SnapPageTags',
  'ConfirmationDialog/ConfirmationDialog',
  'SearchField/SearchField',
]
